---
- hosts: all
  become: true

  tasks: 
   - name: check connectivity
     ping:

 #  - name: move file to /tmp location
 #    command: sudo mv  /var/lib/jenkins/workspace/myfirstjob/target/*.war /tmp/hello.war     
 #    delegate_to: 127.0.0.1

   - name: copy war file to tomcat server
     copy: 
       src: /var/lib/jenkins/workspace/my-ci-cd/target/hello-world-1.1.war
       dest: /usr/local/tomcat/webapps/koti.war
       remote_src: no
  
   - name: restart tomcat service
     shell: service tomcat restart 
