---
- hosts: web
  become : true

  tasks:
  
   - name : copy the build artifacts of maven into webserver
     copy:
       src: /tmp/hello.war
       dest: /opt/bitnami/tomcat/webapps/

   - name: restart apache tomcat
     shell: sudo /opt/bitnami/ctlscript.sh restart apache

     register: command_output

   - debug: msg="{{command_output.stdout}}"

   
     

