---
- hosts: devops
  become : true

  tasks:
   - name : copy the build artifacts of maven into webserver
     copy:
       src: /tmp/hello.war
       dest: /opt/tomcat/webapps/
   - name: restart tomcat server
     service:
        name: tomcat
        state: started

   
     

