---
- hosts: web
  gather_facts: no
  tasks:
  
   - name: checking ping
     ping:
     
   - name: stat foo
     copy:
      src: /tmp/helloworld.war
      dest: /usr/share/tomcat/webapps/

   - name: restart tomcat service
     service:
       name: tomcat
       state: restarted

